### PR TITLE
Token price

### PR DESCRIPTION
**Pull request by Tristyn**

### CODE REVIEW

**Comment by davodesign84** [comment]
when running this branch I get dozens of 429 responses from the rpc node :/
Screenshot 2022-06-07 at 12 46 47

**Comment by Tristyn** [comment]
If your frontend is getting ratelimited with 429, you can open settings in the app, and set this as your rpc node
“https://mango.devnet.rpcpool.com/”

**Comment by Tristyn** [comment]
@davodesign84 good to merge?

**Comment by davodesign84** [comment]
Think so :)

**Review by davodesign84 — APPROVED** [review]

**Pull request merged**
