### PR TITLE
Avoid tokens-to-lamports shenannigans

### PR DESCRIPTION
**Pull request by eyevz**
With jet-v2/fix/risk-slider-interaction,

* fixes JV15-260
* fixes JV15-253

That's the claim, anyway. Please test aggressively.

### CODE REVIEW

**Comment by eyevz** [comment]
The failure is because the corresponding changes to `jet-v2` need to be merged. Unsure how to proceed. Paging @jetjake or @Tristyn.

**Comment by davodesign84** [comment]
@eyevz can you please update the library package.json version in `libraries/ts/package.json` and I'll publish it once merged.

**Review by davodesign84 — APPROVED** [review]

**Comment by davodesign84** [comment]
Tested it locally and seems to work fine, but we are having issues with actual repay instructions, though unrelated to this PR I'd think. :/

**Review by jetjake — APPROVED** [review]
Merge it.

**Pull request merged**
